.TH slackmat\-sync 8 "" "" "slackmatic user's manual"
.\" slackmat-sync.8
.\" man page for slackmat-build
.\" wcm, 2007.04.19 - 2007.04.23
.\" ===
.SH NAME
slackmat\-sync \- syncronize a local archive of slackmatic ports
from one or more distributed repositories
.SH SYNOPSIS
.nf
\fBslackmat\-sync [options]\fP
\fBslackmat\-sync [options] repo [repo ...]
.fi
.SH DESCRIPTION
\fBslackmat\-sync\fP updates a local archive of slackmatic ports
from one or more remote repositories.
A port repository provides the build specifications used by
\fBslackmat\-build\fP to construct Slackware-compliant .tgz packages.
.PP
In the first form of the command,
\fBslackmat\-sync\fP will syncronize
all the remote repositories defined in \fI*.httpup\fP files
in the directory defined by the configuration variable SLACKMAT_SYNCDEFS.
.PP
In the second form of the command, \fBslackmat\-sync\fP will syncronize
each individual <repo> named on the command line that has a corresponding
sync definition file named \fI<repo>.httpup\fP in the directory
defined by SLACKMAT_SYNCDEFS.
.\"
.\" OPTIONS
.\"
.SH OPTIONS
In normal usage no options are required to run \fBslackmat\-sync\fP.
The following options are available for
special configurations and/or modification of default behavior:
.TP
.B "\-c, \-\-config\-file <file>"
Specify configuration file.
Usually \fBslackmat\-sync\fP looks for and reads
its configuration successively from a file named
\fIslackmat.conf\fP in \fI/etc/slackmatic\fP and \fI$HOME/.slackmatic\fP.
(In this way configuration in $HOME may be used to override/modify
the default configuration installed in \fI/etc\fP.)
Use this option to specify an alternative configuration file.
.TP
.B "\-h, \-\-help"
Display brief help message and exit.
.TP
.B "\-L, \-\-local-repobase <dir>"
Specify location of base directory for local repository archive.
Normally remote repositories are synced with the base directory
specified by the configuration variable SLACKMAT_REPOBASE
or in the current working directory if SLACKMAT_REPOBASE is not defined.
(In a default configuration, SLACKMAT_REPOBASE will be set to
\fI$HOME/slackmatic/repos\fB.)
Use this option to set the base directory on the command-line.
.TP
.B "\-S, \-\-sync-defs <dir>"
Specify location of \fI*.httpup\fP sync definitions.
Normally \fBslackmat\-sync\fP looks for \fI*.httpup\fP
sync definitions in the directory specified by the configuration
variable SLACKMAT_SYNCDEFS.
(In a default configuration, SLACKMAT_SYNCDEFS will be set to
\fI/etc/slackmatic/sync\fP.)
Use this option to set the sync definition directory on the
command-line.
.TP
.B "\-T, \-\-notrace"
Suppress the ``trace'' messages generated by \fBslackmat\-build\fP.
.TP
.B "\-U NAME@URL"
Syncronize the remote port repository at URL
to the local directory $SLACKMAT_REPOBASE/NAME.
This is an experimental option (with a questionable syntax!)
to enable specification of individual sync defininitions on the command-line.
Multiple \-U options may be named in an invocation of
\fBslackmat-sync\fP.
.\"
.\" FILES
.\"
.SH FILES
.TP
.I "*.httpup"
A sync definition file takes the form <repo>.httpup
where <repo> is a name used to alias a remote slackmatic port
repository located at a specific url.
This file contains a single definition of the variable
URL.
For example, the \fIslackmatic.httpup\fP sync definition
file contains the definition
\fBURL=http://www.slackmatic.org/repo/\fP.
This provides the sync definition for the repo known as
"slackmatic".
Note that a URL should always be defined with the trailing '/'.
.\"
.\" EXAMPLES
.\"
.SH EXAMPLES
.PP
Use \fBslackmat\-sync\fP to syncronize all remote repositories
with *.httpup definitions installed in \fI/etc/slackmatic/sync\fP:
.PP
.nf
$ slackmat-sync
.fi
.PP
Syncronize only the "slackmatic" and "guinix"
repositories where \fIslackmatic.httpup\fP and
\fIguinix.httpup\fP exist in $SLACKMAT_SYNCDEFS
.PP
.nf
$ slackmat-sync slackmatic guinix
.fi
.PP
Syncronize the repository located at
http://www.slackmatic.org/repo/
into the directory \fI$SLACKMAT_REPOBASE/sm.bak\fP:
.PP
.nf
$ slackmat-sync -U sm.bak@http://www.slackmatic.org/repo/
.fi
.PP
Note that the URL should always be specified with a trailing '/'.
.\"
.\" SEE ALSO
.\"
.SH SEE ALSO
slackmat\-build(8), slackmat\-clean(8),
httpup(8)
.PP
http://www.slackmatic.org/
.\"
.\"
.\" EOF
