.TH slackmat-clean 8 "" "" "slackmatic user's manual"
.\" slackmat-clean.8
.\" man page for slackmat-clean
.\" wcm, 2007.04.19 - 2007.04.19
.\" ===
.SH NAME
slackmat\-clean \- clean-up after a slackmat\-build
.SH SYNOPSIS
\fBslackmat-clean [options]\fP
.SH DESCRIPTION
\fBslackmat-clean\fP cleans up after a \fBslackmat\-build\fP
in the current working directory.
.\"
.\" OPTIONS
.\"
.SH OPTIONS
In normal usage no options are required to run \fBslackmat-clean\fP.
The following options are available for special configurations
and/or modification of default behavior:
.TP
.B "\-a, \-\-archive"
Archive the sources and completed package.
Any remote source files that have downloaded into the
current working directory by \fBslackmat\-build\fP will
be moved to the directory specified by the configuration
variable SLACKMAT_DISTFILES.
The most recently completed .tgz file named in \fIpackage\fP
will be moved to the directory specified by the configuration
variable SLACKMAT_PKGFILES.
This is currently the default action
unless OPT_ARCHIVE=0 has been specified in \fIslackmat.conf\fP.
.TP
.B "\-A, \-\-noarchive"
Do not archive sources and/or the most recently completed package.
.TP
.B "\-B, \-\-build\-file <file>"
Specify alternative build file.
Usually \fBslackmat\-build\fP runs the build controlled by the
file \fIBUILD.rc\fP in the current directory.
Use this option to clean-up after a \fBslackmat\-build\fP
has specified an alternative build file.
.TP
.B "\-c, \-\-config\-file <file>"
Specify configuration file.
Usually \fBslackmat\-clean\fP looks for and reads
its configuration successively from
\fIslackmat.conf\fP files in \fI/etc/slackmatic\fP and \fI$HOME/.slackmatic\fP.
(In this way configuration in $HOME may be used to override/modify
the default configuration installed in \fI/etc\fP.)
Use this option to specify an alternative configuration file.
.TP
.B "\-h, \-\-help"
Display brief help message and exit.
.TP
.B "\-p, \-\-pkg-archive <dir>"
Specify directory to archive package.
Normally packages are archived in the directory configured with
the variable SLACKMAT_PKGFILES.
Use this option to set the package archive directory on the command-line.
.TP
.B "\-s, \-\-source\-archive <dir>"
Specify directory to archive source files.
Normally sources are archived in the directory configured with
the variable SLACKMAT_DISTFILES.
Use this option to set the source archive directory on the command-line.
.TP
.B "\-T, \-\-notrace"
Suppress the ``trace'' messages generated by \fBslackmat\-clean\fP.
.\"
.\" EXAMPLES
.\"
.SH EXAMPLES
.PP
Use \fBslackmat\-clean\fP to clean-up after a successful build:
.PP
.nf
$ cd path/to/someport
$ slackmat-build && slackmat-clean
.fi
.\"
.\" SEE ALSO
.\"
.SH SEE ALSO
slackmat\-build(8), slackmat\-sync(8),
rc(1)
.PP
http://www.slackmatic.org/
.\"
.\"
.\" EOF
